provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  openfaas-ocr:
    lang: Dockerfile
    handler: ./openfaas-ocr
    # image: viveksyngh/openfaas-ocr:0.3.0
    image: mbilalce/ocr:0.1.0
    environment:
      read_timeout: 600s
      write_timeout: 600s
      exec_timeout: 600s
    limits: 
      memory: 2048Mi
      cpu: 1000m